### ISSUE TITLE
Chat bubble not expanding vertically if i type a lot

### ISSUE THREAD

**Issue by bt1** [LoganWright/SimpleChat#32] opened 2015-10-01 20:30 UTC
When I input about 10 lines of text into the text bubble, they start to break and cover over the messages after that.

**Comment by LoganWright** [comment] 2015-10-02 19:39
Hi @bt1,

I'm unable to reproduce this error, 10+ lines is running fine for me.  Can you verify that you're on the latest version, and perhaps provide steps necessary to recreate the error?

Best,

Logan

**Comment by LoganWright** [comment] 2015-10-08 14:03
closing as cannot reproduce.

**Closed** 2015-10-08 14:03 UTC
